version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/myapp
      - ~/.m2:/root/.m2
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
