name: Run Maven Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' # Eclipse Temurin is the successor to AdoptOpenJDK

    - name: Run Maven Test
      run: mvn test -Dspring.profiles.active=test
