name: MongoDB Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust the Java version as needed

      - name: Build and Test
        run: |
          mvn clean install -DskipTests=true
          mvn test -Dspring.data.mongodb.uri=mongodb://mongodb:27017/BT-Store

